version: '3'
services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - db
      
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes: 
      - postgres:/var/lib/postgresql/data
volumes:
  odoo:
  postgres: